### ISSUE TITLE
Mobs with armor causes crash?

### ISSUE THREAD

**Issue by GIANTCRAB** [SilentChaos512/ScalingHealth#222]
## Versions

- **Scaling Health**: 1.14.4-2.3.14+41
- **Silent Lib**: SilentLib-1.14.4-4.4.0+44
- **Forge**: 28.2.0
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/giantcrabby-modpack
- **Optifine Installed**: No

## Expected Behavior

Difficulty is gained when killing mobs. As difficulty increases, mobs will start spawning with armor. Players will be able to fight them

## Actual Behavior

Difficulty is gained when killing mobs. As difficulty increases, mobs will start spawning with armor. Server crashes immediately.

## Links/Images
```[10Feb2020 06:17:46.401] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.item.Item.func_200296_o()Lnet/minecraft/util/text/ITextComponent;
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: com.progwml6.ironchest.common.ai.CatsSitOnChestsHandler@1090d8ff changeSittingTaskForOcelots(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		2: ASM: net.silentchaos512.scalinghealth.event.PetEventHandler@5916a9d9 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		3: ASM: class net.silentchaos512.scalinghealth.event.DifficultyEvents onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		4: ASM: class net.silentchaos512.scalinghealth.event.BlightHandler onBlightUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		5: ASM: class net.silentchaos512.gems.chaos.ChaosHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		6: ASM: class com.mushroom.midnight.common.CommonEventHandler onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		7: ASM: shadows.apotheosis.ench.EnchModule@1edd3e07 lifeMend(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
java.lang.NoSuchMethodError: net.minecraft.item.Item.func_200296_o()Lnet/minecraft/util/text/ITextComponent;
	at net.silentchaos512.scalinghealth.utils.EquipmentTierMap.equip(EquipmentTierMap.java:150)
	at net.silentchaos512.scalinghealth.config.equipment.BootsConfig.processMob(BootsConfig.java:66)
	at net.silentchaos512.scalinghealth.utils.SHMobEquipment.equipBoots(SHMobEquipment.java:91)
	at net.silentchaos512.scalinghealth.utils.SHMobEquipment.equipAll(SHMobEquipment.java:15)
	at net.silentchaos512.scalinghealth.utils.MobDifficultyHandler.setEntityProperties(MobDifficultyHandler.java:93)
	at net.silentchaos512.scalinghealth.utils.MobDifficultyHandler.process(MobDifficultyHandler.java:30)
	at net.silentchaos512.scalinghealth.capability.DifficultyAffectedCapability.tick(DifficultyAffectedCapability.java:70)
	at net.silentchaos512.scalinghealth.event.DifficultyEvents.lambda$onLivingUpdate$2(DifficultyEvents.java:71)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)
	at net.silentchaos512.scalinghealth.event.DifficultyEvents.onLivingUpdate(DifficultyEvents.java:70)
	at net.minecraftforge.eventbus.ASMEventHandler_154_DifficultyEvents_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:312)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1963)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at net.minecraft.entity.monster.MonsterEntity.func_70071_h_(SourceFile:51)
	at net.minecraft.entity.monster.CreeperEntity.func_70071_h_(CreeperEntity.java:142)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587)
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:748)

[10Feb2020 06:17:46.406] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:833) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.Item.func_200296_o()Lnet/minecraft/util/text/ITextComponent;
	at net.silentchaos512.scalinghealth.utils.EquipmentTierMap.equip(EquipmentTierMap.java:150) ~[?:2.3.14+41]
	at net.silentchaos512.scalinghealth.config.equipment.BootsConfig.processMob(BootsConfig.java:66) ~[?:2.3.14+41]
	at net.silentchaos512.scalinghealth.utils.SHMobEquipment.equipBoots(SHMobEquipment.java:91) ~[?:2.3.14+41]
	at net.silentchaos512.scalinghealth.utils.SHMobEquipment.equipAll(SHMobEquipment.java:15) ~[?:2.3.14+41]
	at net.silentchaos512.scalinghealth.utils.MobDifficultyHandler.setEntityProperties(MobDifficultyHandler.java:93) ~[?:2.3.14+41]
	at net.silentchaos512.scalinghealth.utils.MobDifficultyHandler.process(MobDifficultyHandler.java:30) ~[?:2.3.14+41]
	at net.silentchaos512.scalinghealth.capability.DifficultyAffectedCapability.tick(DifficultyAffectedCapability.java:70) ~[?:2.3.14+41]
	at net.silentchaos512.scalinghealth.event.DifficultyEvents.lambda$onLivingUpdate$2(DifficultyEvents.java:71) ~[?:2.3.14+41]
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?]
	at net.silentchaos512.scalinghealth.event.DifficultyEvents.onLivingUpdate(DifficultyEvents.java:70) ~[?:2.3.14+41]
	at net.minecraftforge.eventbus.ASMEventHandler_154_DifficultyEvents_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:312) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1963) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?]
	at net.minecraft.entity.monster.MonsterEntity.func_70071_h_(SourceFile:51) ~[?:?]
	at net.minecraft.entity.monster.CreeperEntity.func_70071_h_(CreeperEntity.java:142) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?]
	... 4 more
```

## Steps to Reproduce the Problem

1. Gain difficulty by killing mobs
2. Mobs with armor attempt to spawn?
3. Server crashes

**Comment by Cyborgmas** [comment]
Weird bug, I'll only be able to fix it this weekend, for now you can empty the list of armor in the config file to get rid of bug.
