### ISSUE TITLE
ScalingHealth Crashing entity

### ISSUE THREAD

**Issue by RubenRDC** [SilentChaos512/ScalingHealth#358]
## Versions
1.16.5

- **Scaling Health**: 4.1.5+11 / 4.0.5+5
- **Silent Lib**: 4.9.6
- **Forge**: 36.1.32
- **Modpack**: (List of modifications in the crash report)

## Expected Behavior
I hope it does not close and revive without problems

(Description here)

## Actual Behavior
When dying and trying to revive the server crashes
(Description here)

## Links/Images

- https://pastebin.com/WAWmihYm
- https://drive.google.com/file/d/1zkoCFD9YwjkfkcLdUym-lW1EmO-2X5-e/view?usp=sharing (registration without downloading)

## Steps to Reproduce the Problem

1. They kill me or I die and when trying to reappear the server crashes

**Comment by RubenRDC** [comment]
10.07 21:37:48 [Server] INFO [RubenGZ: Killed RubenGZ]
10.07 21:37:48 [Server] INFO The player RubenGZ has successfully been saved
10.07 21:37:49 [Server] INFO Player lost 0.00 heart crystal(s)
10.07 21:37:49 [Server] INFO Player gained 0.00 difficulty
10.07 21:37:49 [Server] ERROR Exception caught during firing event: Could not access capability
10.07 21:37:49 [Server] INFO Index: 1
10.07 21:37:49 [Server] INFO Listeners:
10.07 21:37:49 [Server] INFO 0: LOWEST
10.07 21:37:49 [Server] INFO 1: ASM: class net.silentchaos512.scalinghealth.event.ScalingHealthCommonEvents onLevelChange(Lnet/minecraftforge/event/entity/player/PlayerXpEvent$LevelChange;)V
10.07 21:37:49 [Server] INFO java.lang.IllegalStateException: Could not access capability
10.07 21:37:49 [Server] INFO at net.silentchaos512.scalinghealth.utils.SHPlayers.lambda$getPlayerData$0(SHPlayers.java:19)
10.07 21:37:49 [Server] INFO at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:299)
10.07 21:37:49 [Server] INFO at net.silentchaos512.scalinghealth.utils.SHPlayers.getPlayerData(SHPlayers.java:19)
10.07 21:37:49 [Server] INFO at net.silentchaos512.scalinghealth.event.ScalingHealthCommonEvents.onLevelChange(ScalingHealthCommonEvents.java:115)
10.07 21:37:49 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_257_ScalingHealthCommonEvents_onLevelChange_LevelChange.invoke(.dynamic)
10.07 21:37:49 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
10.07 21:37:49 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
10.07 21:37:49 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
10.07 21:37:49 [Server] INFO at net.minecraft.entity.player.PlayerEntity.func_82242_a(PlayerEntity.java:1725)
10.07 21:37:49 [Server] INFO at net.minecraft.entity.player.ServerPlayerEntity.func_82242_a(ServerPlayerEntity.java:456)
10.07 21:37:49 [Server] INFO at net.minecraft.entity.player.ServerPlayerEntity.reset(ServerPlayerEntity.java:1995)
10.07 21:37:49 [Server] INFO at net.minecraft.server.management.PlayerList.moveToWorld(PlayerList.java:773)
10.07 21:37:49 [Server] INFO at net.minecraft.server.management.PlayerList.func_232644_a_(PlayerList.java:647)
10.07 21:37:49 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:2119)
10.07 21:37:49 [Server] INFO at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:30)
10.07 21:37:49 [Server] INFO at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8)
10.07 21:37:49 [Server] INFO at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$1(PacketThreadUtil.java:28)
10.07 21:37:49 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
10.07 21:37:49 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152)
10.07 21:37:49 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
10.07 21:37:49 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:899)
10.07 21:37:49 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:179)
10.07 21:38:00 [Multicraft] Server shut down (running)
10.07 21:38:00 [Multicraft] Restarting crashed server in 5 seconds
10.07 21:38:00 [Multicraft] Server stopped
10.07 21:38:00 [Disconnect] User RubenGZ has disconnected, reason: Server shutting down

**Comment by RubenRDC** [comment]
https://pastebin.com/41qKGR29

https://pastebin.com/pK3ZzVtz
