### ISSUE TITLE
Is there a version for a regular server?

### ISSUE THREAD

**Issue by TheDenigo** [SilentChaos512/ScalingHealth#449]
The mod does not work on the server. Is there a version to run on the server?
An error occurs in the Minecraft server. It occurs due to an attempt to load the net.minecraft.server.integrated class.Integrated Server in the wrong context is DEDICATED_SERVER, which is used only for dedicated servers, not integrated ones.

It can be seen from the call stack that the error occurs in the class DifficultyEvents from the Scaling Health mod. There is probably code in this class that tries to load the Integrated Server class in a context that is intended only for dedicated servers.

To solve this problem, you need to edit the code of the DifficultyEvents class and remove the code that causes an error when loading the IntegratedServer class. How to do it?

**Comment by TheDenigo** [comment]
This problem is present on 1.16.5
When a player logs off the server, a save error occurs due to this mod.
Tell me how to fix your joint or fix it yourself!

**Comment by TheDenigo** [comment]
[23:25:00] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/server/integrated/IntegratedServer for invalid dist DEDICATED_SERVER
[23:25:00] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/server/integrated/IntegratedServer for invalid dist DEDICATED_SERVER
        Index: 9
        Listeners:
                0: NORMAL
                1: ASM: com.github.alexthe666.citadel.server.CitadelEvents@4f8637fe onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                2: ASM: com.github.alexthe666.citadel.server.CitadelEvents@4f8637fe onEntityUpdateDebug(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                3: ASM: class net.smileycorp.hordes.common.infection.InfectionEventHandler onTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                4: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@718105a1 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                5: ASM: class com.alexander.mutantmore.events.DoMutationsEvent affectEntities(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                6: ASM: class com.alexander.mutantmore.events.BonusEffects affectEntities(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                7: ASM: class com.github.alexthe666.rats.server.events.CommonEvents onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                8: ASM: class net.silentchaos512.scalinghealth.event.PetEventHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                9: ASM: class net.silentchaos512.scalinghealth.event.DifficultyEvents onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                10: ASM: class net.silentchaos512.scalinghealth.event.BlightHandler onBlightUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                11: ASM: class com.brandon3055.brandonscore.handlers.BCEventHandler livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                12: ASM: class com.brandon3055.draconicevolution.handlers.ModularArmorEventHandler livingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                13: ASM: vazkii.quark.content.tweaks.module.DragonScalesModule@3f143868 onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                14: ASM: vazkii.quark.content.tweaks.module.PoisonPotatoUsageModule@1c333515 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                15: ASM: vazkii.quark.content.world.module.BiotiteModule@6f1afeb4 onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                16: ASM: com.inventorypets.events.PlayerTickHandler@197c5a53 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                17: ASM: com.inventorypets.events.GravePetHandler@25fa2728 gravePetLoadEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                18: ASM: com.inventorypets.events.ItemEntityEvents@44d55247 handleLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                19: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@6d333c47 tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                20: ASM: com.someguyssoftware.treasure2.eventhandler.CharmEventHandler@58795a4c checkCharmsInteraction(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                21: ASM: com.github.alexthe666.iceandfire.event.ServerEvents@5cd9439a onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                22: LOWEST
                23: ASM: net.smileycorp.hordes.common.hordeevent.HordeEventHandler@11db9390 update(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
java.lang.RuntimeException: Attempted to load class net/minecraft/server/integrated/IntegratedServer for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at net.silentchaos512.scalinghealth.event.DifficultyEvents.onLivingUpdate(DifficultyEvents.java:81)
        at net.minecraftforge.eventbus.ASMEventHandler_398_DifficultyEvents_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:326)
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114)
        at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300)
        at com.github.alexthe666.alexsmobs.entity.EntityCrow.func_70071_h_(EntityCrow.java:273)
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612)
        at net.minecraft.world.World.func_217390_a(World.java:554)
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.lang.Thread.run(Unknown Source)

[23:25:00] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 9457b8e7-a56f-471b-9863-272ca0216d8f
[23:25:00] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_391] {}
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/server/integrated/IntegratedServer for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[forge-1.16.5-36.2.39.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_391] {}
        at net.silentchaos512.scalinghealth.event.DifficultyEvents.onLivingUpdate(DifficultyEvents.java:81) ~[scalinghealth:4.1.4+10] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_398_DifficultyEvents_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:326) ~[forge:?] {re:classloading}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.LivingEntityMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:memoryleakfix-16.mixins.json:entityMemoriesLeak.LivingEntity_clearMemoriesMixin,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:takesapillage.mixins.json:MobRememberSpawnReasonMixin,pl:mixin:APP:hordes.mixin.json:MixinMobEntity,pl:mixin:APP:letmedespawn.mixins.json:MobMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at com.github.alexthe666.alexsmobs.entity.EntityCrow.func_70071_h_(EntityCrow.java:273) ~[alexsmobs:1.12.0] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.entity_load_deadlock.ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:memoryleakfix-16.mixins.json:drownedNavigationLeak.ServerLevel_navigationMixin,pl:mixin:APP:ksyxis.mixins.json:ServerLevelMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.block_entity_ticking.collections.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.block_entity_ticking.should_tick_cache.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.block_entity_ticking.support_cache.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:APP:ksyxis.mixins.json:LevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.entity_load_deadlock.ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:memoryleakfix-16.mixins.json:drownedNavigationLeak.ServerLevel_navigationMixin,pl:mixin:APP:ksyxis.mixins.json:ServerLevelMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        ... 5 more
[23:25:00] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: D:\My serv forge 10\.\crash-reports\crash-2023-12-17_23.25.00-server.txt
[23:25:00] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[23:25:00] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[23:25:00] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: qq_noob lost connection: Internal Exception: java.lang.StackOverflowError
[23:25:00] [Server thread/INFO] [minecraft/DedicatedServer]: qq_noob left the game
[23:25:00] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.world.server.ServerWorld.removeEntity(ServerWorld.java:950) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.entity_load_deadlock.ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:memoryleakfix-16.mixins.json:drownedNavigationLeak.ServerLevel_navigationMixin,pl:mixin:APP:ksyxis.mixins.json:ServerLevelMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.removePlayer(ServerWorld.java:971) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.entity_load_deadlock.ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:memoryleakfix-16.mixins.json:drownedNavigationLeak.ServerLevel_navigationMixin,pl:mixin:APP:ksyxis.mixins.json:ServerLevelMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_217434_e(ServerWorld.java:967) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.entity_load_deadlock.ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:memoryleakfix-16.mixins.json:drownedNavigationLeak.ServerLevel_navigationMixin,pl:mixin:APP:ksyxis.mixins.json:ServerLevelMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:339) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147231_a(ServerPlayNetHandler.java:1021) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:366) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.flushconsolidation.ClientConnectionMixin,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.pipeline.compression.ClientConnectionMixin,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.pipeline.encryption.ClientConnectionMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213167_f(SourceFile:79) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.play.ServerPlayNetHandler.func_194028_b(ServerPlayNetHandler.java:296) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.management.PlayerList.func_72392_r(PlayerList.java:742) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:557) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:514) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:679) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_391] {}
