### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by brotazoa** [SilentChaos512/ScalingHealth#56]
Minecraft Version: 1.12.2
Forge Version: 14.23.0.2531
Scaling Health Version: 1.12-1.3.3-79
Silent Lib Version: 1.12-2.2.13.94

Crash log attached

New world, single player, creative, superflat, structures off.
Wait anywhere from 1 to 10 minutes and game crashes to launcher with a NPE.

[crash-2017-11-29_22.02.17-client.txt](https://github.com/SilentChaos512/ScalingHealth/files/1516392/crash-2017-11-29_22.02.17-client.txt)

Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.silentchaos512.scalinghealth.utils.SHPlayerDataHandler.get(SHPlayerDataHandler.java:45)
	at net.silentchaos512.scalinghealth.client.DifficultyDisplayHandler.onRenderOverlay(DifficultyDisplayHandler.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_524_DifficultyDisplayHandler_onRenderOverlay_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:904)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:734)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:172)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by SilentChaos512** [comment]
That's a strange one. Does it happen consistently? Did you add any other mods before this started?

**Comment by brotazoa** [comment]
It happens literally every time. A workaround that I have figured out though, if you create a new world and then immediately save and quit to menu, then open it again... the NPE doesn't happen. So that is pretty strange too. I was browsing through the SHPlayerDataHandler class, and think I have an idea as to what is causing it (which is what lead me to the workaround)

This is with a few other mods, and I am working on the process of elimination, but it might take a minute to narrow it down.
